routes/web.php
<?php


Route::group(['namespace' => 'Web', 'as' => 'web.'], function () {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'home']);

    Route::get('about-us', ['uses' => 'AboutUsController@index', 'as' => 'about-us']);
    Route::get('circles', ['uses' => 'CircleController@index', 'as' => 'circles']);

    Route::get('scopes', ['uses' => 'ScopeController@index', 'as' => 'scopes.index']);
    Route::get('scopes/{slug}', ['uses' => 'ScopeController@show', 'as' => 'scopes.show']);

    Route::get('events', ['uses' => 'EventController@index', 'as' => 'events.index']);
    Route::get('events/{slug}', ['uses' => 'EventController@show', 'as' => 'events.show']);

    Route::get('gold-members', ['uses' => 'MemberController@gold', 'as' => 'gold-members']);
    Route::get('members/{slug}', ['uses' => 'MemberController@show', 'as' => 'members.show']);

    Route::get('calender', ['uses' => 'Test@show', 'as' => 'calender']);
    Route::get('contact-us', ['uses' => 'Test@show', 'as' => 'contact-us']);
});


Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'namespace' => 'Dashboard'], function () {
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');

    Route::group(['middleware' => 'auth'], function () {
        Route::get('home', ['uses' => 'HomeController@index', 'as' => 'home']);

        Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        Route::get('configs', ['uses' => 'ConfigController@edit', 'as' => 'configs.edit']);
        Route::post('configs', ['uses' => 'ConfigController@store', 'as' => 'configs.store']);
        Route::resource('members', 'MemberController');
        Route::resource('events', 'EventController');
        Route::resource('images', 'ImageController');
        Route::resource('speakers', 'SpeakerController');

        Route::group(['prefix' => 'ajax', 'as' => 'ajax.', 'namespace' => 'Ajax'], function () {
            Route::resource('members', 'MemberController');
            Route::resource('events', 'EventController');
            Route::get('images', ['uses' => 'ImageController@index', 'as' => 'images.index']);
            Route::get('images/search', ['uses' => 'ImageController@search', 'as' => 'images.search']);
            Route::get('speakers', ['uses' => 'SpeakerController@index', 'as' => 'speakers.index']);
            Route::get('speakers/search', ['uses' => 'SpeakerController@search', 'as' => 'speakers.search']);
        });
    });
});

app/Http/Controllers/Dashboard/Ajax/EventController.php
<?php

namespace App\Http\Controllers\Dashboard\Ajax;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\EventRepository;
use App\Entities\Event;
use Datatables;
use View;

class EventController extends Controller
{
    public function __construct(EventRepository $events)
    {
        $this->events = $events;
    }

    public function index(Request $request)
    {
        return Datatables::of($this->events->getAjaxIndex()->orderBy('date', 'desc'))
            ->addColumn('actions', function ($row) {
                $editUrl = route('dashboard.events.edit', $row->id);
                $deleteUrl = route('dashboard.events.destroy', $row->id);

                return View::make('dashboard.layouts._formActions', compact('editUrl', 'deleteUrl'));
            })
            ->make(true);
    }
}

app/Http/Controllers/Dashboard/Ajax/ImageController.php
<?php

namespace App\Http\Controllers\Dashboard\Ajax;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\ImageRepository;
use Datatables;
use View;

class ImageController extends Controller
{
    public function __construct(ImageRepository $images)
    {
        $this->images = $images;
    }

    public function index(Request $request)
    {
        return Datatables::of($this->images->getAjaxIndex())
            ->addColumn('actions', function ($row) {
                $editUrl = route('dashboard.images.edit', $row->id);
                $deleteUrl = route('dashboard.images.destroy', $row->id);
                
                return View::make('dashboard.layouts._formActions', compact('editUrl', 'deleteUrl'));
            })
            ->addColumn('image', function($row){
                return $row->image->url('thumb');
            })
            ->make(true);
    }

    public function search(Request $request)
    {
        return $this->images->filterBy($request->search)->pluck('description', 'id')->toArray();
    }
}

app/Http/Controllers/Dashboard/Ajax/MemberController.php
<?php

namespace App\Http\Controllers\Dashboard\Ajax;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\MemberRepository;
use App\Entities\Member;
use Datatables;
use View;

class MemberController extends Controller
{
    public function __construct(MemberRepository $members)
    {
        $this->members = $members;
    }

    public function index(Request $request)
    {
        return Datatables::of($this->members->getAjaxIndex())
            ->addColumn('actions', function ($row) {
                $editUrl = route('dashboard.members.edit', $row->id);
                $deleteUrl = route('dashboard.members.destroy', $row->id);
                
                return View::make('dashboard.layouts._formActions', compact('editUrl', 'deleteUrl'));
            })
            ->addColumn('joined_at', function($row){
                return $row->joined_at ? $row->joined_at->year : null;
            })
            ->make(true);
    }
}

app/Http/Controllers/Dashboard/Ajax/SpeakerController.php
<?php

namespace App\Http\Controllers\Dashboard\Ajax;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\SpeakerRepository;
use App\Entities\Speaker;
use Datatables;
use View;

class SpeakerController extends Controller
{
    public function __construct(SpeakerRepository $speakers)
    {
        $this->speakers = $speakers;
    }

    public function index(Request $request)
    {
        return Datatables::of($this->speakers->getAjaxIndex())
            ->addColumn('actions', function ($row) {
                $editUrl = route('dashboard.speakers.edit', $row->id);
                $deleteUrl = route('dashboard.speakers.destroy', $row->id);

                return View::make('dashboard.layouts._formActions', compact('editUrl', 'deleteUrl'));
            })
            ->addColumn('avatar', function($row){
                return $row->avatar->url('thumb');
            })
            ->make(true);
    }

    public function search(Request $request)
    {
        return $this->speakers->filterBy($request->search)->pluck('name', 'id')->toArray();
    }

}

app/Http/Controllers/Dashboard/ConfigController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\ConfigRepository;
use App\Http\Requests\Dashboard\Config\UpdateRequest;

class ConfigController extends Controller
{
    public function __construct(ConfigRepository $configs)
    {
        $this->configs = $configs;
    }

    /**
     * Show the dashboard home
     *
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        $sliders = $this->configs->getHomeSliderImages();
        return view('dashboard.configs.edit', compact('sliders'));
    }

    public function store(UpdateRequest $request)
    {
        $this->configs->storeSliders($request->sliders);
        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/EventController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\EventRepository;
use App\Http\Requests\Dashboard\Event\CreateRequest;
use App\Http\Requests\Dashboard\Event\UpdateRequest;
use App\Entities\Event;

class EventController extends Controller
{
    public function __construct(EventRepository $events)
    {
        $this->events = $events;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.events.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $event = $this->events->create($request->all());
        $event->speakers()->sync($request->speakers);

        return redirect()->route('dashboard.events.index')->withSuccess('Event Added Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Event $event)
    {
        return view('dashboard.events.edit', compact('event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $event = $this->events->find($id);
        if (!$event) {
            abort(404);
        }
        
        $event->speakers()->sync($request->speakers);
        $this->events->update($request->all(), $event->id);

        return redirect()->route('dashboard.events.index')->withSuccess('Event Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->events->delete($id);

        return redirect()->route('dashboard.events.index')->withSuccess('Event Deleted Successfully');
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Show the dashboard home
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.home');
    }
}

app/Http/Controllers/Dashboard/ImageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\ImageRepository;
use App\Http\Requests\Dashboard\Image\CreateRequest;
use App\Http\Requests\Dashboard\Image\UpdateRequest;
use App\Entities\Image;

class ImageController extends Controller
{
    public function __construct(ImageRepository $images)
    {
        $this->images = $images;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.images.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.images.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $this->images->create($request->all());

        return redirect()->route('dashboard.images.index')->withSuccess('Image Added Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Image $image)
    {
        return view('dashboard.images.edit', compact('image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $this->images->update($request->all(), $id);

        return redirect()->route('dashboard.images.index')->withSuccess('Image Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Image $image)
    {
        if (!$this->images->canDelete($image)) {
            return redirect()->back()->withError('Cannot remove the image. Please check the configs attached with it and try again!');
        }

        $image->delete();

        return redirect()->route('dashboard.images.index')->withSuccess(' Image Deleted Successfully');
    }
}

app/Http/Controllers/Dashboard/MemberController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\MemberRepository;
use App\Http\Requests\Dashboard\Member\CreateRequest;
use App\Http\Requests\Dashboard\Member\UpdateRequest;
use App\Entities\Member;

class MemberController extends Controller
{
    public function __construct(MemberRepository $members)
    {
        $this->members = $members;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.members.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.members.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $this->members->create($request->all());

        return redirect()->route('dashboard.members.index')->withSuccess('Member Added Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Member $member)
    {
        return view('dashboard.members.edit', compact('member'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $this->members->update($request->all(), $id);

        return redirect()->route('dashboard.members.index')->withSuccess('Member Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->members->delete($id);

        return redirect()->route('dashboard.members.index')->withSuccess(' Member Deleted Successfully');
    }
}

app/Http/Controllers/Dashboard/SpeakerController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\SpeakerRepository;
use App\Http\Requests\Dashboard\Speaker\CreateRequest;
use App\Http\Requests\Dashboard\Speaker\UpdateRequest;
use App\Entities\Speaker;

class SpeakerController extends Controller
{
    public function __construct(SpeakerRepository $speakers)
    {
        $this->speakers = $speakers;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.speakers.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.speakers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $this->speakers->create($request->all());

        return redirect()->route('dashboard.speakers.index')->withSuccess('Speaker Added Successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Speaker $speaker)
    {
        return view('dashboard.speakers.edit', compact('speaker'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $this->speakers->update($request->all(), $id);

        return redirect()->route('dashboard.speakers.index')->withSuccess('Speaker Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $speaker = $this->speakers->with('events')->find($id);
        
        if ($speaker->events->count() > 0) {
            return redirect()->route('dashboard.speakers.index')->withWarning('Cannot delete this speaker! Delete his/her events first');
        }

        $this->speakers->delete($id);

        return redirect()->route('dashboard.speakers.index')->withSuccess(' Speaker Deleted Successfully');
    }
}

resources/views/dashboard/speakers/_form.blade.php
<div class="row">
  <div class="col-lg-3">
    <div class="form-group @if($errors->first('name')) has-error @endif">
      <label class="control-label" for="name">Name</label>
      {{ Form::text('name', old('name'), ['class' => 'form-control', 'id' => 'name']) }}
      @if($errors->first('name')) <span class="help-block">{{ $errors->first('name') }}</span> @endif
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-3">
    <div class="form-group @if($errors->first('avatar')) has-error @endif">
      <label for="avatar" class="control-label">Avatar</label>
      @if(isset($speaker))
        <div class="row">
          <div class="col-lg-4">
            <a href="{{ $speaker->avatar->url() }}" target="_blank"><img src="{{ $speaker->avatar->url('thumb') }}"></a>
          </div>
        </div><br>
        {!! Form::file('avatar', ['class' => 'custom-file-input']) !!}
      @else
        {!! Form::file('avatar', ['class' => 'custom-file-input', 'required' => true]) !!}
      @endif
      @if($errors->first('avatar')) <span class="help-block">{{ $errors->first('avatar') }}</span> @endif
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-3">
    <div class="form-group @if($errors->first('linkedin')) has-error @endif">
      <label class="control-label" for="linkedin">Linkedin Profile</label>
      {{ Form::text('linkedin', old('linkedin'), ['class' => 'form-control', 'id' => 'linkedin']) }}
      @if($errors->first('linkedin')) <span class="help-block">{{ $errors->first('linkedin') }}</span> @endif
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-9">
    <div class="form-group @if($errors->first('bio')) has-error @endif">
      <label class="control-label" for="bio">Content</label>
      {{ Form::textarea('bio', old('bio'), ['class' => 'form-control', 'id' => 'bio']) }}
      @if($errors->first('bio'))<span class="help-block">{{ $errors->first('bio') }}</span>@endif
      </div>
    </div>
</div>

@section('footerScripts')
  <script>
    require(['ckeditor'], function($){
      CKEDITOR.replace('bio', {
        language : 'ar'
      });
    });
  </script>
@endsection

resources/views/dashboard/speakers/create.blade.php
@extends('dashboard.layouts.app')

@section('title')
  Add Speaker
@stop

@section('content')
  <div class="row">
    <div class="col-lg-12">
      <div class="box-body">
        {!! Form::open(['route' => 'dashboard.speakers.store', 'files' => 'true']) !!}
          @include('dashboard.speakers._form')
          <div class="form-actions">
            <div class="form-group">
              <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
              <button type="submit" class="btn btn-danger" onclick="window.location='{{ route('dashboard.speakers.index') }}';">Back</button>
            </div>
          </div>
        {{ Form::close() }}
      </div>
    </div>
  </div>
@endsection

resources/views/dashboard/speakers/edit.blade.php
@extends('dashboard.layouts.app')

@section('title')
  Edit Event
@stop

@section('content')
  <div class="row">
    <div class="col-lg-12">
      {{ Form::model($speaker, ['route' => ['dashboard.speakers.update', $speaker->id], 'method' => 'PATCH', 'files' => 'true']) }}
        @include('dashboard.speakers._form')
        <div class="form-actions">
          <div class="form-group">
            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
            <button type="submit" class="btn btn-danger" onclick="window.location='{{ route('dashboard.speakers.index') }}';">Back</button>
          </div>
        </div>
      {{ Form::close() }}
    </div>
  </div>
@endsection

resources/views/dashboard/speakers/index.blade.php
@extends('dashboard.layouts.app')

@section('title')
  Speakers
@stop

@section('styles')
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css">
@endsection

@section('content')
  <div class="box">
    <div class="box-body">
      <button type="button" class="btn bg-olive margin" onclick="window.location='{!! route('dashboard.speakers.create') !!}'">Add Speaker</button>
      <table id="speakers-table" class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Avatar</th>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>
      </table>
    </div>
  </div>
@endsection

@section('footerScripts') 
  <script>
    require(['jquery', 'datatables.net', 'dataTables'], function($, DataTable){
      $('#speakers-table').DataTable( {
        serverSide: true,
        processing: true,
        ajax: {
          url: '{!! route('dashboard.ajax.speakers.index') !!}'
        },
        columns: [
          { data: 'avatar',
            render: function(data){
              return '<img src="' + data + '">';
            }
          },
          { data: 'name' },
          {
            data: "actions",
            render: function(data){
              return htmlDecode(data);
             }
          }
        ]
      });
    });
  </script>
@endsection